@startuml couper-texte
hide footbox
skinparam sequenceMessageAlign center

actor Utilisateur
participant "Editeur de texte"

activate Utilisateur
activate "Editeur de texte"

== Accès à la plateforme ==

Utilisateur -> "Editeur de texte": Demande l'accès à la plateforme
Utilisateur <-- "Editeur de texte": Accepte la demande

== Sélection du texte ==

Utilisateur -> "Editeur de texte": Sélectionne du texte
Utilisateur <-- "Editeur de texte": Affiche en surbrillance le texte sélectionné

== Coupage de la sélection ==

Utilisateur -> "Editeur de texte": Presse Ctrl + X pour couper la sélection
alt La sélection est vide
Utilisateur <-- "Editeur de texte": Vide le presse-papier
else
Utilisateur <-- "Editeur de texte": Stocke et écrase le contenu dans le presse-papier
Utilisateur <-- "Editeur de texte": Enlève le contenu sélectionné du texte
end

deactivate Utilisateur
deactivate "Editeur de texte"
@enduml