@startuml
interface Command {
    + execute() : void
}

class MoveCursorCommand {
    - textEditor : TextEditor&
    - start : unsigned long long
    - end : unsigned long long
    + MoveCursorCommand(TextEditor& textEditor, \nunsigned long long start, \nunsigned long long end)
    + ~MoveCursorCommand()
}

class EnterCharCommand {
    - textEditor : TextEditor&
    - start : unsigned long long
    - end : unsigned long long
    - character : char
    + EnterCharCommand(TextEditor& textEditor, \nunsigned long long start, \nunsigned long long end, \nchar character) 
    + ~EnterCharCommand()
}

class DeleteTextCommand {
    - textEditor : TextEditor&
    - start : unsigned long long
    - end : unsigned long long
    + DeleteTextCommand(TextEditor& textEditor, \nunsigned long long start, \nunsigned long long end)
    + ~DeleteTextCommand()
}

class CopyCommand {
    - textEditor : TextEditor&
    - start : unsigned long long
    - end : unsigned long long
    + CopyCommand(TextEditor& textEditor, \nunsigned long long start, \nunsigned long long end)
    + ~CopyCommand()
}

class PasteCommand {
    - textEditor : TextEditor&
    - start : unsigned long long
    - end : unsigned long long
    + PasteCommand(TextEditor& textEditor, \nunsigned long long start, \nunsigned long long end)
    + ~PasteCommand()
}

class CutCommand {
    - textEditor : TextEditor&
    - start : unsigned long long
    - end : unsigned long long
    + CutCommand(TextEditor& textEditor, \nunsigned long long start, \nunsigned long long end)
    + ~CutCommand()
}

class Client {
    - textEditor : TextEditor
    - renderer : Renderer
    - pollEvent() : void
    + Client(int width, int height)
    + run()
}

class Renderer {
    - int width : 
    - int height : 

    - TTF_Font* font : 
    - SDL_Renderer* renderer{} : 
    - SDL_Window* window{} : 

    + void drawText(std::string text, size_t cursorStart, size_t cursorEnd) const : 
    + void drawCursor(int x, int y, int w, int h) const : 
    + void render() const : 
    + Renderer(int width, int height) : 
    + void clear() const : 
    + void resize(int width, int height) : 

    + ~Renderer() : 
}

class TextEditor {
    - command : Command
    - textBuffer : string
    - clipboard : string
    - selectionStart : int
    - selectionEnd : int
    + draw(renderer : Renderer) : void
    + setCommand(cmd : Command) : void
    + executeCommand() : void
    + undoCommand() : void
    +keyPressedctrl : boolean, alt : boolean, Key : string
}


Command <|.. MoveCursorCommand
Command <|.. EnterCharCommand
Command <|.. DeleteTextCommand
Command <|.. CopyCommand
Command <|.. PasteCommand
Command <|.. CutCommand

TextEditor o--> Command
Client --> Renderer

Client --> TextEditor
@enduml