@startuml classDiagram
interface Command {
    + execute() : void
    + undo() : void
}

class MoveCursorCommand {
}

class EnterCharCommand {
}

class DeleteTextCommand {
}

class CopyCommand {
}

class PasteCommand {
}

class CutCommand {
}

class Client {
    - textEditor : TextEditor
    - renderer : Renderer
    - event : SDL_event
    - pollEvent() : void
    + run()
}

class Renderer {
    - renderer: SDL_Renderer;
    - width : int
    - height : int
    - fontPath : string
    - resize() : void

    + Renderer(...)
    + clear()
    + ~Renderer()
}

class TextEditor {
    - command : Command
    - textBuffer : string
    - clipboard : string
    - selectionStart : int
    - selectionEnd : int
    + draw(renderer : Renderer) : void
    + setCommand(cmd : Command) : void
    + executeCommand() : void
    + undoCommand() : void
    +keyPressedctrl : boolean, alt : boolean, Key : string
}


Command <|.. MoveCursorCommand
Command <|.. EnterCharCommand
Command <|.. DeleteTextCommand
Command <|.. CopyCommand
Command <|.. PasteCommand
Command <|.. CutCommand

TextEditor o--> Command
Client --> Renderer

Client --> TextEditor

@enduml