@startuml
hide footbox
skinparam sequenceMessageAlign center

actor Utilisateur
participant "Editeur de texte"
participant "EnterCharCommand"

activate Utilisateur
activate "Editeur de texte"

== Accès à la plateforme ==

Utilisateur -> "Editeur de texte": Demande l'accès à la plateforme
Utilisateur <-- "Editeur de texte": Accepte la demande

== Entrée du texte ==

Utilisateur -> "Editeur de texte": Appuie sur une lettre/caractère

alt Texte sélectionné
  "Editeur de texte" -> "EnterCharCommand": Remplace le texte sélectionné
else Pas de texte sélectionné
  "Editeur de texte" -> "EnterCharCommand": Insère le caractère
end

activate "EnterCharCommand"

alt Caractère non autorisé
  "EnterCharCommand" -> "Editeur de texte": Remplace le caractère par '#'
else Caractère autorisé
  "EnterCharCommand" -> "Editeur de texte": Ajoute le caractère au `textBuffer`
end

"EnterCharCommand" -> "Editeur de texte": Met à jour la position du curseur
deactivate "EnterCharCommand"

"Editeur de texte" -> Utilisateur: Mise à jour du texte à afficher

deactivate Utilisateur
deactivate "Editeur de texte"
@enduml